# See all available variables at https://megalinter.io/latest/config-file/
# and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

## Commands:
PRE_COMMANDS:
  - command: npm ci
    cwd: "workspace"
  - command: npm install eslint-plugin-react-refresh@latest --save-dev
    cwd: "root"

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - SPELL # Comment to enable checks of spelling mistakes

DISABLE_LINTERS:
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - COPYPASTE_JSCPD

JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (tsconfig.json)

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

RUBY_RUBOCOP_CONFIG_FILE: deploy/.rubocop.yml

MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: (README.md)
