# See all available variables at https://megalinter.io/latest/config-file/
# and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

## Commands:
PRE_COMMANDS:
  - command: npm ci
    cwd: "workspace"

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - SPELL # Comment to enable checks of spelling mistakes

JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (tsconfig.json)

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
