---
name: Install runtimes
description: Install the required runtimes and related base dependencies

runs:
  using: "composite"
  steps:
    - name: Determine versions
      shell: bash -leo pipefail {0}
      id: get_versions
      run: |
        ruby="$(grep -v '#' .tool-versions | grep ruby | awk '{print $2}')"
        echo "ruby=${ruby}" >> $GITHUB_OUTPUT

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.get_versions.outputs.ruby }}
        bundler-cache: true
