---
name: Deploy
description: Deploy the project

inputs:
  environment:
    description: "Environment name"
    required: true
  aws_access_id:
    description: "AWS access ID"
    required: true
  aws_secret_key:
    description: "AWS secret key"
    required: true
  aws_region:
    description: "AWS region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Show tooling information
      shell: bash -leo pipefail {0}
      run: aws --version

    - name: Run deployment
      shell: bash -leo pipefail {0}
      run: deploy/deploy.rb -e ${{ inputs.environment }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
        AWS_REGION: ${{ inputs.aws_region}}
