---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/CommandLiteral:
  EnforcedStyle: mixed

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
